---

# import playbooks from playbooks directory
- import_playbook: playbooks/example.yml
  # add optional custom tags
  tags:
    - example

# import more

# vim: set ft=yaml.ansible syn=yaml sw=2 ts=2 et colorcolumn=160 :
# eof
